name: Deploy to FTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 45.132.157.19
          username: u983503200.Grupo2703
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Esto sube todos los archivos del repositorio
          server-dir: /G2/  # Asegúrate de que esta ruta sea correcta y termine con '/'
